$ANSIBLE_VAULT;1.1;AES256
33383864333462376335306133313632333961626138383865306334636463393637323534333331
3030633335363636336234646237613235623061316561650a353837366365373165343937623663
33326130313733343432303239613063666364333435303734373835373662303033323536343664
3037376535643432320a306139383132353335373262623333363564306239323533383134363233
38333532386538626430663035356337656336613662656666326333656139666265