 - name: disable default nginx 
   ansible.builtin.command: dnf module disable nginx -y

- name: enable nginx:1.24 
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx 
  ansible.builtin.dnf:
    name: nginx 
    state: present 

- name: remove html directory 
  ansible.builtin.file: 
    path: /usr/share/nginx/html/* 
    state: absent 

- name: create html directory 
  ansible.builtin.file: 
    path: /usr/share/nginx/html/* 
    state: directory  

- name: Download frontend application code 
  ansible.builtin.get_url: 
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip 
    dest: /tmp/frontend.zip 

- name: extract frontend application 
  ansible.builtin.unarchive: 
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html 
    remote_src: yes  

- name: Delete default nginx conf 
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent 

- name: copy nginx conf 
  ansible.builtin.copy: 
    src: nginx.conf 
    dest: /etc/nginx/nginx.conf
  
- name: Restart nginx 
  ansible.builtin.service:
    name: nginx 
    state: restarted  # restarted if you have already started earlier
    enabled: yes 
  
     